// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLXxhO19vX9XXB9lNh7_i03nCvP65bKJo',
    appId: '1:377799740812:web:3ff7f94f491439ec829aa9',
    messagingSenderId: '377799740812',
    projectId: 'food-cafe-user',
    authDomain: 'food-cafe-user.firebaseapp.com',
    storageBucket: 'food-cafe-user.firebasestorage.app',
    measurementId: 'G-6P7CFZMN07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcLYQmRtiOXp3KUZQ8zJEbewBF4tDJtq8',
    appId: '1:377799740812:android:9d6f646b6e4e0b54829aa9',
    messagingSenderId: '377799740812',
    projectId: 'food-cafe-user',
    storageBucket: 'food-cafe-user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6h7xTuyFA6luryZIPiDJZRI5zoQz-TQ',
    appId: '1:377799740812:ios:03a8b8d0552b22d5829aa9',
    messagingSenderId: '377799740812',
    projectId: 'food-cafe-user',
    storageBucket: 'food-cafe-user.firebasestorage.app',
    iosBundleId: 'com.example.foodCafeUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo6h7xTuyFA6luryZIPiDJZRI5zoQz-TQ',
    appId: '1:377799740812:ios:03a8b8d0552b22d5829aa9',
    messagingSenderId: '377799740812',
    projectId: 'food-cafe-user',
    storageBucket: 'food-cafe-user.firebasestorage.app',
    iosBundleId: 'com.example.foodCafeUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLXxhO19vX9XXB9lNh7_i03nCvP65bKJo',
    appId: '1:377799740812:web:f04c71fd56de5b8c829aa9',
    messagingSenderId: '377799740812',
    projectId: 'food-cafe-user',
    authDomain: 'food-cafe-user.firebaseapp.com',
    storageBucket: 'food-cafe-user.firebasestorage.app',
    measurementId: 'G-D55J8S5R70',
  );
}
